cffi/cffi

grovel/invoke.lisp
It is needed if user calls invoke for output (ie pkg-config)
=> ecl: fix second value of %invoke

toolchain/c-toolchain.lisp
This removes read macro written twice, which causes problem on ARM environment, like raspberry pi.
I ran into this problem in
- implementation: SBCL 1.3.4,
- hardware: on raspberry pi Type B 512MB (with ARM 32 bit CPU),
- OS: Raspbian 8.0
while loading CFFI, with the following error message:
```
; caught ERROR:
;   READ error during COMPILE-FILE: unmatched close parenthesisLine: 82, Column: 19, File-Position: 2874Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/pi/.roswell/impls/ALL/ALL/quicklisp/dists/quicklisp/software/cffi_0.17.1/toolchain/c-toolchain.lisp" {53760711}>
While evaluating the form starting at line 6, column 0
of #P"/home/pi/.roswell/impls/ALL/ALL/quicklisp/dists/quicklisp/software/static-vectors-1.6/static-vectors.asd":
Unhandled LOAD-SYSTEM-DEFINITION-ERROR: Error …
```
=> Fix read macro probromatic in ARM CPU.

doc/cffi-manual.texinfo, src/early-types.lisp, src/structures.lisp, src/types.lisp
Very basic implementation of the feature. Almost a copy-paste of `expand-from-foreign`. Is used from `#'mem-set`.
I have tested with my projects and get the desired expansion.
I haven't added any tests to the suite as I don't see any tests the output of the current `expand-*` functions. If this is wrong please tell me how you'd like them written and I'll get that done.
=> Added expand-into-foreign-memory

toolchain/c-toolchain.lisp
On Windows7+MSYS, the output of pkg-config as read by CCL included
\#RETURN.
I added #\Return the bag of separators.  I also reformatted the code a
bit, to make it a bit more readable (fewer long lines or ackward line
splits).
=> parse-command-flags: Added #\Return to separators

toolchain/asdf-compat.lisp
It's only present in newer ASDFs and is basically a COND with
macroexpansion-time test evaluation. The code that uses it is not
performance critical.
=> Avoid using uoip:os-cond.

src/cffi-ecl.lisp
This is for bytecmp and the C compiler compatibility. :cdecl doesn't
work on Android, but :default works just fine. For C compiled code there
is no difference.
This patch will trigger itself on the upcoming ECL release (16.1.3) and is backward-compatible. Tested with cffi-tests – no regressions found (both with "fake" 16.1.3 version of ECL and 16.1.2).
=> ecl: defcallback: fix calling-convention

src/cffi-abcl.lisp
Recent change to jna in ABCL causes breakage of CFFI. Patch provided by
ferada.
=> cffi-abcl: fix foreign-alloc/foreign-free

cffi.asd
Dependency on `uiop' can't be implicit for sake of `program-op' and
`image-op' builds. User may wish to not include `asdf' or `cmp' (in case
of ECL) in the final image.
ASDF has option (require-system :system) which doesn't reload it, if
it's already present in the image (even if it's newer):
https://common-lisp.net/project/asdf/asdf.html#index-require_002dsystem
so (:require :uiop) shouldn't reload the system. That said, ASDF doesn't
handler (:require :system-name) options correclty yet, treating them
like normal dependencies. But this will be forward-compatible when ASDF
will fix that.
Closes #96.
=> system: re-add dependency on UIOP as :require

src/c2ffi/generator.lisp
I was getting warnings about `:ns` from function and constant so I have added them to the 'expected' lists.
=> c2ffi now exports ns tags for function & constant

src/c2ffi/asdf.lisp, src/c2ffi/generator.lisp
This allows the user to provide a predicate to determine which of the generated symbols will be exported from the cffi/c2ffi specified package.
By default no symbols are exported (so that the current behaviour is maintained)
The predicate is specified in same the fashion as :ffi-type-transformer & :ffi-name-transformer
```
:ffi-export-predicate "test-c2ffi.ffi::ffi-export-predicate"
```
The predicate function has the following form
```
(defun ffi-export-predicate (symbol)
(alexandria:starts-with-subseq "NK-" (symbol-name symbol)))
```
We also switch to using `uiop`'s `define-package` so that using `asdf:load-system :force t` doesnt throw errors when it hits `defpackage`
=> add ffi-export-predicate

src/types.lisp
This brings this function in line with foreign-slot-value.
=> Add foreign-slot-pointer compiler macro

src/c2ffi/generator.lisp
The problem with this that with forms like this:
typedef enum {
dJointTypeNone = 0,
dJointTypeBall,
dJointTypeHinge,
} dJointType;
The enum is always excluded, as the name is nil. Then the `dJointType`
typedef tries too lookup the anonomous entry for the enum and fails.
The only way to counter it is to have explicitly include the definitions
for everything in the files (which makes it feel much less automatic).
This commit is one possible fix. Another is to allow the user to
customize the `include-definition?` predicate. Also `cl-autowrap`
handles this case so maybe we can take some inspiration from there.
The worrying thing of course is that this is a potentially breaking change
=> Null name shouldnt satisfy strong rules

src/c2ffi/generator.lisp
Otherwise it crashes the first time it tries to read one. The example
case for me was in:
#define DBL_EPSILON __DBL_EPSILON__
=> *read-default-float-format* should be double-float

cffi-toolchain.asd
The dependencies were subtly wrong: when the ASDF loaded was already > 3.1.6,
then the asdf-compat was blackholed by its if-feature condition,
which broke the chain of dependencies for package.
=> Fix dependencies in cffi-toolchain.asd

src/libraries.lisp
When `:search-path` is specified in library definition and `load-foreign-library` called, if cffi searches for `:or` alternatives, it won't find those in the provided `:search-path`, because these paths are not propagated into search function.
=> Propagate search-path when searching for alternatives.

grovel/asdf.lisp, toolchain/c-toolchain.lisp
Shared objects were failing to link on the latest SBCL because it specifies
-fno-pie in its CFLAGS, but that invalidates the previously specified -fPIC.
Fix that by specifying -fPIC *after* the SBCL-provided CFLAGS, not *before*.
Also, remove a redundant use of -fPIC, and fix a comment.
=> Fix dynamic linking with SB-LINKABLE-RUNTIME

toolchain/static-link.lisp
Configure and upgrade ASDF before loading quicklisp.
=> Make static linking more resilient to ASDF upgrade

src/types.lisp, tests/arrays.lisp
Rename test ARRAY.ROUND-TRIP to ARRAY.FOREIGN-TO-LISP.BASIC
Add test ARRAY.FOREIGN-TO-LISP.ADJUSTABLE
Add test ARRAY.FOREIGN-TO-LISP.DISPLACED
Add test ARRAY.FOREIGN-TO-LISP.SPECIALIZED
Implementation detail for test ARRAY.FOREIGN-TO-LISP.SPECIALIZED:
15.1.2.2 of the standard states that the only truly portable array specializations are for bits (bit-vectors) and characters (strings). Since char-codes are implementation-dependent, it would be tricky to write a portable test for them without generating characters at runtime. So, for a truly portable test, we are only left with bits, which are luckily numeric, and equal to (UNSIGNED-BYTE 1).
This is why this test is so terribly wasteful, spending a whole byte for a single bit - CFFI has no capabilities for dealing with single bits, and this …
=> Add &REST MAKE-ARRAY-ARGS to #'FOREIGN-ARRAY-TO-LISP

doc/cffi-manual.texinfo, grovel/grovel.lisp, tests/grovel.lisp
This adds a new groveller form `feature` that detects if a preprocessor constant is defined, and adds a value to `*features*` if the constant is present. This is intended to be used when a C library defines preprocessor constants if it was compiled with certain functionality.
=> Add groveller syntax to detect if preprocessor constants are defined

src/enum.lisp
KEYWORDP can't be constant folded, since a symbol could be uninterned
after compilation, so using a more general type gets rid of some
style warnings on SBCL. %FOREIGN-ENUM-VALUE has an explicit check for
ENUM-KEY, so that is probably more correct than KEYWORD anyway.
=> check for ENUM-KEY instead of KEYWORD in foreign enum translators

src/libraries.lisp
`darwin-fallback-library-path` doesn't support the MacPorts library path `/opt/local/lib`, causing issues like https://github.com/dimitri/pgloader/issues/161 and https://github.com/dimitri/pgloader/issues/444
This patch adds the MacPorts library path before `/usr/local/lib` and `/usr/lib`.
I successfully tested it on MacOS X 10.14.3, MacPorts 2.5.4, SBCL 1.5.0 and pgloader 3.6.4ec8613.
=> Add MacPorts lib/ to darwin-fallback-library-path

libffi/libffi-types.lisp, libffi/libffi.lisp
This makes CFFI work with libffi `3.3_rc0`+, as `ABI_SYSV` was removed there. I'm not sure if it'd continue to work with lower versions, but it should, since `ABI_UNIX64` was there all along.
=> Make the library work with libffi.so.7

cffi-toolchain.asd
ECL has a ASDF forked from version 3.1.7 version and tags it as
3.1.8 (to avoid confusion, official release following 3.1.7 is
3.2.0). This version has some bugs fixed (especially regarding
bundles) for ECL, so loading this file reintroduces said issues. Since
there is no "official" ASDF 3.1.8 release this change doesn't impact
anything except ECL.
Issue in question is regression with init names, monolithic bundles
and file causes all systems depending on it to loaded twice before
they really are compiled.
=> cffi-toolchain: don't reintroduce bugs to ECL's ASDF

toolchain/c-toolchain.lisp
clang on osx ignores archives built with ar, fix this
https://stackoverflow.com/questions/20663645/ignoring-file-lib-a-file-was-built-for-archive-which-is-not-the-architecture-be/30970680#30970680
=> Use libtool on OSX instead of ar

src/cffi-abcl.lisp
* this allows the ABCL varargs tests to pass
=> on ABCL add :default keyword default arg to %foreign-funcall

src/cffi-sbcl.lisp
When we have `:darwin`, `%load-foreign-library` calls out to `call-within-initial-thread`, apparently due to some macos weirdness. `call-within-initial-thread` interrupts the main thread to load the foreign library, and then waits on a semaphore to indicate that the load was successful. If SBCL is built with `--without-sb-thread`, the above semaphore will block indefinitely since it is both not provided a timeout (unnecessary here anyway) and because SBCL has the following in its logic for `%condition-wait`:
```
#-sb-thread
(sb-ext:wait-for nil :timeout timeout) ; Yeah...
```
This PR extends the condition in `%load-foreign-library` to include `:sb-thread`. If we do not have `:sb-thread` then we should not be concerned about being in the initial thread since that ought to be true by …
=> Don't wait on semaphore if no :SB-THREAD feature available.

src/early-types.lisp, tests/struct.lisp
CFFI now always translates aggregate struct values to lisp property
lists.  Earlier struct values which were defined by types introduced
by defctype were translated as foreign pointers.
One consequence of this change is that defcvar to a foreign structure
will always produce an immutable lisp list. Users will have to resort
to FOREIGN-SYMBOL-VALUE in order to access structs to modify them -
and use the (:POINTER VAR) syntax of WITH-FOREIGN-SLOTS to access and
modify fields within the struct.
* src/early-types.lisp: (defctype): use translatable-foreign-type
instead of enhanced-foreign-type.
* tests/structs.lisp: New tests: (misnamed) STRUCT-VALUES.FSBV.1
STRUCT-VALUES.FSBV.1 Updated tests: STRUCT.ALIGNMENT.1
STRUCT.ALIGNMENT.2 STRUCT.ALIGNMENT.3 STRUCT.ALIGNMENT.4
STRUCT.ALIGNMENT.5 …
=> fix translation of struct-typedefs

doc/cffi-manual.texinfo, src/enum.lisp, tests/enum.lisp
This is useful for very large enumerations of which we're only interested in a subset, or enumerations that allow for arbitrary client or vendor extensions that we cannot be aware of. Erroring on a value that we ostensibly do not care about in such a situation is not desirable, and instead simply passing through the integer allows handling the interesting cases easily in a CASE or something similar.
If there's any style inconsistencies or other changes I should make, please let me know.
=> Implement an enum flag that elides an error when translating an enum value that was not declared.

doc/cffi-manual.texinfo, src/libraries.lisp, src/package.lisp
* add option :CANARY to DEFINE-FOREIGN-LIBRARY: a foreign symbol unique
to the library
If that symbol is found in the current image before
the first attempt to load the library, the latter is assumed to be
statically linked and LOAD-FOREIGN-LIBRARY only marks the load state
as :STATIC before returning.
* add new slot LOAD-STATE which, together with HANDLE, tracks the
library
| library state     | LOAD-STATE | HANDLE  |
|-------------------|------------|---------|
| not loaded        | NIL        | NIL     |
| statically linked | :STATIC    | NIL     |
| dlopen()'d        | :EXTERNAL  | non-NIL |
=> Detect statically linked libraries and avoid loading

toolchain/c-toolchain.lisp
For example:
```lisp
(defsystem "foo"
:components ((:c-file "foo" :cflags ("-lz" "-lm"))))
```
The slot is already there, but isn't actually used. It's useful when
custom compilation options need to be passed.
Additionally, the cflags slot is removed from o-file, as it does not
make sense there. Nor is it used, anyway.
=> Do not ignore cflags of c-file.

src/cffi-abcl.lisp
In abcl-1.7.0, CL:MAKE-ARRAY is able create and share ```malloc()```d memory
for java.nio.ByteVector allocated by JNA via use of the ```:NIO-BUFFER```
argument. Whether this feature is present in the current
implementation is conditionalized on the presence ```:NIO``` in
```CL:*FEATURES*```.
We retain the old behavior of copying memory for
WITH-POINTER-TO-VECTOR-DATA when passed a non-shareable byte vector as
a plausible fallback strategy.
supersedes #165
=> abcl: implement MAKE-SHAREABLE-BYTE-VECTOR

toolchain/c-toolchain.lisp
I believe all symbols are default exported w/the Solaris linker
=> Solaris ld doesn't do --export-dynamic

src/libraries.lisp
In Mac OS Big Sur, system dynamic libraries are no longer present on the filesystem and reside in the dynamic linker cache. This change searches for the framework directory instead of the dynamic library underneath the framework directory. 
https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes
New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the …
=> Added support for finding frameworks on Mac OS Big Sur

src/utils.lisp
When a list has one element, `(cdr list)` is nil, so it  must be negated in `discard-docstring` for the condition to ever be true in the correct circumstances.
Without this change, calls to `defcstruct` and `defcunion` with a docstring and no slots fails with the same error:
``` common lisp
(cffi:defcstruct foo "docstring")
;; Error while parsing arguments to DESTRUCTURING-BIND:
;; invalid number of elements in
;;   "docstring"
;; to satisfy lambda list
;;   (CFFI::SLOTNAME TYPE &KEY (COUNT) CFFI::OFFSET):
;; at least 2 expected, but got a non-list
;;  [Condition of type SB-KERNEL::ARG-COUNT-ERROR]
(cffi:defcunion bar "Union docstring")
;; Error while parsing arguments to DESTRUCTURING-BIND:
;; invalid number of elements in
;;   "Union docstring"
;; to satisfy lambda list
;; …
```
=> Fix macro discard-docstring

src/libraries.lisp
* This is the (current) default path for arm64 homebrew
libraries. Try this before the rest.
=> on arm64 macos check /opt/homebrew/lib for libraries first

src/cffi-abcl.lisp
When a foreign function is not found by `find-foreign-function` (either because
the function doesn't exist, or because the library is not loaded), `nil` is
returned, so `%%foreign-funcall` is called with `nil` as a function, which
ultimately leads to a null-pointer exception.
Better to signal an error on the lisp side.
=> Signal an error when a foreign function is not found on ABCL.

doc/cffi-manual.texinfo, src/types.lisp, tests/struct.lisp
Now accepts with-slots-like bindings (name slotname), as well as (name :pointer slotname).  All in all a binding may be one of:
```
name                       name bound to slot of same name              
(:pointer name)            name bound to pointer to slot of same name
(name slot-name)           name bound to slot-name
(name :pointer slot-name)  name bound to pointer to slot-name
```
Rationale:   
Lispers expect binding forms to provide the ability to bind chosen names.  The inability of `with-foreign-slots`to do so is both surprising and disappointing.  It makes it awkward to use `with-foreign-slots` in functions that happen to bind symbols that happen to coincide with slot names:
```
(defun point-init (point x y)
(with-foreign-slots ((x y) point  (:struct point))
(setf x... …
```
=> Improved with-foreign-slots binding abilities to allow local names for slots

grovel/grovel.lisp
Report a bad package designator in (IN-PACKAGE :FOO) as
The name :FOO does not designate any package.
instead of
The value
NIL
is not of type
PACKAGE
=> grovel: Error message for IN-PACKAGE with bad package designator

libffi/libffi.lisp
I was tempted to load libffi.so and libffi32.so, to make this future-proof, but I didn't dare to be so bold :-)
~~Sorry, this is not tested yet, but I will do that if we don't have CI :-)~~ Seems to work!
=> Support libffi.so.8/libffi32.so.8 (unix) and libffi-8.dll (windows)

.travis.yml, tests/bindings.lisp, tests/test-asdf.lisp
* build all branches
* test more implementations (but only SBCL and CCL are mandatory)
* libffi-dev is now installed by cl-travis
* disable TEST-STATIC-PROGRAM because it fails due to sbcl.o not being
build with -fPIE
* print unexpected failures at the end of the test run
=> Use lispci/cl-travis as CI integration

src/cffi-sbcl.lisp
Where variadic arguments are not just passed normally.
To pass all the tests the latest revision of SBCL from git is required, as the CFFI test suite uncovered a bug there.
=> Support variadic functions on SBCL-Darwin-arm64.

grovel/grovel.lisp, tests/grovel-test.h, tests/grovel.lisp
This allows the groveler to correctly handle cstruct definitions that include arrays
=> Handle numbers correctly in CFFI-GROVEL::C-WRITE

src/c2ffi/c2ffi.lisp
Added the `#+arm64` branch to `local-cpu`, to be able to generate the `.spec` file for `aarch64-apple-darwin9`.
Although not necessary for this fix, other updates in `cl-autowrap` were included; I can remove them if needed.
The following example now correctly generates the `.spec` file for `aarch64-apple-darwin9` when `c2ffi` is available in the path:
```lisp
(defsystem "cimgui-cffi"
:version "0.1.0"
:author ""
:license ""
:defsystem-depends-on (:cffi/c2ffi)
:depends-on ("cffi"
"cffi/c2ffi"
"cffi-libffi"
"cl-change-case"
"str")
:pathname "cimgui-cffi"
:serial t
:components
((:file "package")
(:file "prelude")
(:module "spec"
:components
((:cffi/c2ffi-file
"cimgui.h"
:package #:cimgui.lib
:foreign-library-name "cimgui"
:ffi-name-transformer "cimgui-cffi.prelude::ffi-name-transformer" …
```
=> Import latest local-cpu and *target-archs* from cl-autowrap

src/functions.lisp, tests/defcfun.lisp
There was a discussion here: https://gitlab.common-lisp.net/cmucl/cmucl/-/issues/74.
This workaround allows to define foreign functions with `defcfun` without loading the corresponding foreign library first on CMUCL.
=> (maybe temporary) workaround for defcfun.undefined test on CMUCL

doc/cffi-manual.texinfo
+ Fix syntax and example to show the correct syntax
+ Add missing macro parameter descriptions
+ Rewrite the macro description to be a bit more clear on exactly what
the macro is doing.
Fixes #335.
=> Fix / Improve with-foreign-pointer-as-string in manual

grovel/grovel.lisp
Should fix https://github.com/cffi/cffi/issues/376. Can't test it though.
=> Fix use of ALEXANDRIA:FORMAT-SYMBOL

doc/cffi-manual.texinfo, src/cffi-ecl.lisp, src/package.lisp, src/types.lisp, tests/defcfun.lisp, tests/memory.lisp
Also fix feature expression for SCL that used long-double instead of long-float.
=> Add support for ECL long double

grovel/grovel.lisp
Hey. I'm being bitten by the fact that grovel subsystem interprets `pkg-config` stderr as the compilation flags for GCC, while its stderr usually contains some kind of warnings. 
This small PR fixes the problem by redirecting stderr of `pkg-config` called by groveller to `*debug-io*`.
=> grovel: don't treat pkg-config stderr as compilation flags

src/cffi-abcl.lisp
JSS has a table of class names that it builds by scanning jar files on the classpath but not directories. (Maybe that's on purpose in case the user has on the classpath a large directory intended to be probed for class files but not recursively scanned.)
So rather than rely on such heuristics from JSS, it's more robust to pass JSS the full correct case-sensitive class name. That lets cffi work even when the JNA library is provided as a directory of class files instead of a jar file. Otherwise cffi only works when JNA is provided as a jar file.
=> Look up CallbackReference class robustly
